; Root PlatformIO entry point.
; Use `-e assignment-01-led-flow` or `-e assignment-02-serial-password`.

[platformio]
src_dir = .
default_envs = assignment-02-serial-password

[env]
platform = espressif32
board = denky32
framework = arduino
upload_port = COM4
monitor_port = COM4
monitor_speed = 115200
upload_speed = 115200

[env:assignment-01-led-flow]
build_src_filter =
    -<*>
    +<assignment-01-led-flow/src/main.cpp>

[env:assignment-02-serial-password]
build_src_filter =
    -<*>
    +<assignment-02-serial-password/src/main.cpp>
