; Root PlatformIO entry point.
; Use `-e led-flow`, `-e serial-led-control`, `-e serial-password-box`,
; `-e stepper-motor`, or `-e oled-display`.

[platformio]
src_dir = .
default_envs = oled-display

[env]
platform = espressif32
board = denky32
framework = arduino
upload_port = COM4
monitor_port = COM4
monitor_speed = 115200
upload_speed = 115200

[env:led-flow]
build_src_filter =
    -<*>
    +<01-led-flow/src/main.cpp>

[env:serial-led-control]
build_src_filter =
    -<*>
    +<02-01-serial-led-control/src/main.cpp>

[env:serial-password-box]
build_src_filter =
    -<*>
    +<02-02-serial-password-box/src/main.cpp>

[env:stepper-motor]
build_src_filter =
    -<*>
    +<03-stepper-motor/src/main.cpp>

[env:oled-display]
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
build_src_filter =
    -<*>
    +<04-oled-display/src/main.cpp>
