; Root PlatformIO entry point.
; Use `-e led-flow`, `-e serial-led-control`, or `-e serial-password-box`.

[platformio]
src_dir = .
default_envs = serial-led-control

[env]
platform = espressif32
board = denky32
framework = arduino
upload_port = COM4
monitor_port = COM4
monitor_speed = 115200
upload_speed = 115200

[env:led-flow]
build_src_filter =
    -<*>
    +<01-led-flow/src/main.cpp>

[env:serial-led-control]
build_src_filter =
    -<*>
    +<02-01-serial-led-control/src/main.cpp>

[env:serial-password-box]
build_src_filter =
    -<*>
    +<02-02-serial-password-box/src/main.cpp>
